### ISSUE TITLE
ブログ機能(ポストCMSみたいなの)を追加したい

### ISSUE THREAD

**Issue by yum45f** [CoderDojo-Konan-Okayama/coderdojo-konan.jp#8]
主にこれが本丸であり、かなり大掛かりになりそう。
今は Page、StaticPage、とあって、それぞれ MDとERB（HTML）で対応しているけど、
ブログも MD で書くけど、 GitHub を使えないスタッフも投稿できるようにしたい。
＝ GUI で完結できるようなページも一緒に作らねば。
# ToDo Tasks List ⚒ (とりあえず)
- [ ] User Model に Uid と Role
- [ ] Post Model （Scaffold）に contents, title, published_at, author, updated_at, slug
- [ ] Post Model の Edit、Create は User Role とか。

**Comment by yu-san-19** [comment]
ただ、今の Pages 的な感じの手軽さも欲しいところ...

**Comment by yu-san-19** [comment]
http://system.blog.uuum.jp/entry/Rails5%E3%81%A7%E6%89%8B%E6%97%A9%E3%81%8FCMS%E9%96%8B%E7%99%BA%E3%82%92%E3%81%99%E3%82%8B%E3%81%AE%E3%81%AB%E4%BE%BF%E5%88%A9%E3%81%AAgem7%E9%81%B8

**Comment by yu-san-19** [comment]
ま、モチベ上げるためにデザインの方から...
https://github.com/akveo/blur-admin

**Comment by yu-san-19** [comment]
そろそろやり始めるかな。
どのようにすればよいのかが...
とりあえず、モデルの構成を考えよう。

**Comment by yu-san-19** [comment]
使えるかも。
http://system.blog.uuum.jp/entry/Rails5%E3%81%A7%E6%89%8B%E6%97%A9%E3%81%8FCMS%E9%96%8B%E7%99%BA%E3%82%92%E3%81%99%E3%82%8B%E3%81%AE%E3%81%AB%E4%BE%BF%E5%88%A9%E3%81%AAgem7%E9%81%B8

**Comment by yu-san-19** [comment]
素直に Scaffold を使って...
アカウント認証は Slack に任せたりできないだろうか。
（なるべく作業を軽くしたい。認証とかは投げたい...）

**Comment by yu-san-19** [comment]
https://api.slack.com/docs/oauth

これとか参考になりそう。

**Comment by yu-san-19** [comment]
User モデルに uid と role を追加する具合でいいかも。
あとは Post モデルを Scaffold で...

**Comment by yu-san-19** [comment]
ログインセッションの管理が課題なんだよな... 🤔

**Comment by yu-san-19** [comment]
ま、とりあえずプロトタイプというか試作というかをやってみよう。
User Model に Uid と Role を作る。
Post Model に contents, title, published_at, author その他必要そうなカラム含んで...

**Comment by yu-san-19** [comment]
# ToDo Tasks List ⚒ (とりあえず)
- [ ] User Model に Uid と Role
- [ ] Post Model （Scaffold）に contents, title, published_at, author, updated_at, slug
- [ ] Post Model の Edit、Create は User Role とか。

**Comment by yu-san-19** [comment]
Slack の omniauth があった。素晴らしい。
https://github.com/kmrshntr/omniauth-slack

**Comment by yu-san-19** [comment]
どっちかというとプレス的な感じで、軽ーくかければ... となってきた。
と、なるとまた MD ファイルを変換して、ちょっと書式を工夫して、という感じになるかな...

**Comment by yu-san-19** [comment]
ちょっとどっちが良いかわからないから、二つのbranch切ってどっちもでやってみよう。 ⚒

**Comment by yu-san-19** [comment]
仮にブログ型とすれば Admin とかのネームスペースを組まねば。

**Comment by yu-san-19** [comment]
ぎゃっ Scaffold の生成が Haml で出てきてる。
...けどこれはこのままにいっそ全部 Haml に変更しよう。

**Comment by yu-san-19** [comment]
ちょっとこのままこのissueを膨らませてると整理がつかないので機能別に別Issuesに切り出そう。

**Comment by yu-san-19** [comment]
friendly_id を使おうか...
別に使わなくても作れるけど...

**Comment by yu-san-19** [comment]
friendly_id は slug カラムに slug を入れるけど、それは slug が nil の場合のみなので、
最初から slug に値が入っているこの仕様ではデフォルトでは難しいということが分かった。
should_generate_new_friendly_id? をPosts モデルでオーバーライドすることにしよう。
